In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
sent=[  'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [20]:
voc_size=10000
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
one_hot_rep=[one_hot(word,voc_size) for word in sent]
one_hot_rep

[[208, 2433, 1272, 8686],
 [208, 2433, 1272, 8120],
 [208, 3982, 1272, 1315],
 [4023, 3244, 9301, 3080, 8933],
 [4023, 3244, 9301, 3080, 236],
 [3210, 208, 6227, 1272, 9053],
 [1308, 828, 197, 3080]]

In [22]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [23]:
import numpy as np
import pandas as pd

In [24]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  208 2433 1272 8686]
 [   0    0    0    0  208 2433 1272 8120]
 [   0    0    0    0  208 3982 1272 1315]
 [   0    0    0 4023 3244 9301 3080 8933]
 [   0    0    0 4023 3244 9301 3080  236]
 [   0    0    0 3210  208 6227 1272 9053]
 [   0    0    0    0 1308  828  197 3080]]


In [25]:
dim=10

In [30]:
# Create model with explicit input shape
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))

# Force model to build by providing sample input shape
model.build(input_shape=(None, sent_length))

# Compile the model
model.compile(optimizer='adam', loss='mse')

c:\Users\Suhail.DESKTOP-0CIIIA7\OneDrive\Desktop\New folder\ann\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [31]:
model.summary()


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


array([[[-0.03725367, -0.02285516, -0.04946792, -0.04421756,
         -0.00535221, -0.04603845,  0.00026923, -0.02792065,
          0.01764734,  0.02496864],
        [-0.03725367, -0.02285516, -0.04946792, -0.04421756,
         -0.00535221, -0.04603845,  0.00026923, -0.02792065,
          0.01764734,  0.02496864],
        [-0.03725367, -0.02285516, -0.04946792, -0.04421756,
         -0.00535221, -0.04603845,  0.00026923, -0.02792065,
          0.01764734,  0.02496864],
        [-0.03725367, -0.02285516, -0.04946792, -0.04421756,
         -0.00535221, -0.04603845,  0.00026923, -0.02792065,
          0.01764734,  0.02496864],
        [-0.00017447,  0.04020562, -0.00343775,  0.04017143,
         -0.02706041, -0.02906598, -0.00903808,  0.03146854,
         -0.01076717,  0.01933551],
        [-0.0491427 , -0.02231178, -0.02914718,  0.03086643,
         -0.03736196, -0.01990183, -0.04742643,  0.04367988,
         -0.04816148,  0.00833576],
        [ 0.00361097,  0.02186804, -0.03542758,  0.0